paths:
  data:
    raw_path: "/content/Gen-AI-for-Data-Augmentation/data/oxford-iiit-pet/images"
    processed_path: "data/processed"
    models_path: "data/models"

dataset:
  num_classes: 37
  train_test_split: 0.2
  validation_split: 0.1

preprocessing:
  image:
    size: [224, 224] 
    normalize: true
    channels: 3 
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

augmentation:
  enabled: true
  train:
    random_rotation: 20
    random_horizontal_flip: true
    random_vertical_flip: false
    random_brightness_contrast: true

training:
  batch_size: 32
  num_epochs: 50
  learning_rate: 0.0001
  optimizer: "adam"
  scheduler:
    name: "cosine"
    T_max: 50
    eta_min: 1e-6
  early_stopping:
    patience: 10
    min_delta: 0.001

model:
  name: "resnet50"
  pretrained: true
  num_classes: 37
  dropout_rate: 0.5